### PR TITLE
feat: consolidate repos

### PR DESCRIPTION
**Pull request by JoeWang1127**

### CODE REVIEW

**Comment by suztomo** [comment]
Let's get the 3 required Kokoro jobs pass at least for appengine-plugins-core and app-maven-plugin modules, before merging this pull request.

**Comment by JoeWang1127** [comment]
Kokoro-ubentu build failed:
```
testDeployStandard: INFO: submitting command: /root/.cache/google-cloud-tools-java/managed-cloud-sdk/LATEST/google-cloud-sdk/bin/gcloud app deploy /tmpfs/src/github/appengine-plugins/app-maven-plugin/target/test-classes/projects/standard-project/target/appengine-staging/app.yaml /tmpfs/src/github/appengine-plugins/app-maven-plugin/target/test-classes/projects/standard-project/target/appengine-staging/WEB-INF/appengine-generated/cron.yaml /tmpfs/src/github/appengine-plugins/app-maven-plugin/target/test-classes/projects/standard-project/target/appengine-staging/WEB-INF/appengine-generated/dispatch.yaml /tmpfs/src/github/appengine-plugins/app-maven-plugin/target/test-classes/projects/standard-project/target/appengine-staging/WEB-INF/appengine-generated/dos.yaml /tmpfs/src/github/appengine-plugins/app-maven-plugin/target/test-classes/projects/standard-project/target/appengine-staging/WEB-INF/appengine-generated/index.yaml /tmpfs/src/github/appengine-plugins/app-maven-plugin/target/test-classes/projects/standard-project/target/appengine-staging/WEB-INF/appengine-generated/queue.yaml --version GCLOUD_VERSION --project travis-app-maven-plugin
Exit code: 1
testDeployStandard: [INFO] GCLOUD: ERROR: (gcloud.app.deploy) argument --version/-v: Bad value [GCLOUD_VERSION]: May only contain lowercase letters, digits, and hyphens. Must begin and end with a letter or digit. Must not exceed 63 characters.
testDeployStandard: [INFO] GCLOUD: Usage: gcloud app deploy [DEPLOYABLES ...] [optional flags]
testDeployStandard: [INFO] GCLOUD:   optional flags may be  --appyaml | --bucket | --cache | --help |
testDeployStandard: [INFO] GCLOUD:                          --ignore-file | --image-url | --promote |
testDeployStandard: [INFO] GCLOUD:                          --service-account | --stop-previous-version | --version
testDeployStandard: [INFO] GCLOUD: 
testDeployStandard: [INFO] GCLOUD: For detailed information on this command and its flags, run:
testDeployStandard: [INFO] GCLOUD:   gcloud app deploy --help
```

I deleted `GCLOUD_VERSION` in [commit](https://github.com/GoogleCloudPlatform/appengine-plugins/pull/966/commits/79238358f3f345b9d9ad12ae6cc9108e7d0735bb).

The error became:

```
testDeployStandard: INFO: submitting command: /root/.cache/google-cloud-tools-java/managed-cloud-sdk/LATEST/google-cloud-sdk/bin/gcloud app deploy --version 1 --project travis-app-maven-plugin
testDeployStandard: [INFO] GCLOUD: ERROR: (gcloud.app.deploy) Permissions error fetching application [apps/travis-app-maven-plugin]. Please make sure that you have permission to view applications on the project and that kokoro-docker-reader@kokoro.google.com.iam.gserviceaccount.com has the App Engine Deployer (roles/appengine.deployer) role.
```

**Comment by suztomo** [comment]
I think you're in the right direction. The environment setup in app-maven-plugin's Kokoro job needs to come here.

**Comment by JoeWang1127** [comment]
Unit test run with Java 17 and 21 failed because Gradle 6.9 is not compatible with Java 17/21.

**Comment by JoeWang1127** [comment]
> I believe Gradle is not used in the two. In that case skip app-gradle-plugin there.

I skipped Gradle project when Java is 17 and 21.

Now the unit tests are successfully.

**Pull request merged**
