### PR TITLE
chore: release appengine-plugins-core 0.10.1

### PR DESCRIPTION
**Pull request by suztomo**
This commit was made via apply_current_versions.sh after
updating versions.txt:

```
$ vim versions.txt
$ ~/google-cloud-java/generation/apply_current_versions.sh
```

### CODE REVIEW

**Comment by suztomo** [comment]
Now unit-tests (8) - unit-tests (21) succeeded.

**Comment by JoeWang1127** [comment]
The group id is wrong.
```
09:23:54:334 [INFO] Performing remote staging...
09:23:54:334 [INFO] 
09:23:54:334 [INFO]  * Remote staging into staging profile ID "52cfdb1a88f8"
09:23:54:967 [INFO]  * Created staging repository with ID "comgooglecloud-6887".
09:23:54:967 [INFO]  * Staging repository at https://google.oss.sonatype.org:443/service/local/staging/deployByRepositoryId/comgooglecloud-6887
09:23:54:968 [INFO]  * Uploading locally staged artifacts to profile com.google.cloud
09:26:20:867 [INFO]  * Upload of locally staged artifacts finished.
09:26:20:868 [INFO]  * Closing staging repository with ID "comgooglecloud-6887".

Waiting for operation to complete...
........

09:26:44:124 [ERROR] Rule failure while trying to close staging repository with ID "comgooglecloud-6887".
09:26:44:125 [ERROR] 
09:26:44:125 [ERROR] Nexus Staging Rules Failure Report
09:26:44:125 [ERROR] ==================================
09:26:44:125 [ERROR] 
09:26:44:125 [ERROR] Repository "comgooglecloud-6887" failures
09:26:44:125 [ERROR]   Rule "pom-staging" failures
09:26:44:125 [ERROR]     * Invalid POM: /com/google/cloud/tools/appengine-maven-plugin/2.5.1/appengine-maven-plugin-2.5.1.pom: Project URL missing, License information missing, Developer information missing
09:26:44:125 [ERROR] 
09:26:44:125 [ERROR] 
09:26:44:125 [ERROR] Cleaning up local stage directory after a Rule failure during close of staging repositories: [comgooglecloud-6887]
09:26:44:125 [ERROR]  * Deleting context 52cfdb1a88f8.properties
09:26:44:126 [ERROR] Cleaning up remote stage repositories after a Rule failure during close of staging repositories: [comgooglecloud-6887]
09:26:44:126 [ERROR]  * Dropping failed staging repository with ID "comgooglecloud-6887" (Rule failure during close of staging repositories: [comgooglecloud-6887]).
```

**Review by JoeWang1127 — APPROVED** [review]

**Comment by suztomo** [comment]
Waiting for 2.5.1 to appear in 2.5.1 in https://repo1.maven.org/maven2/com/google/cloud/tools/appengine-maven-plugin/

**Comment by suztomo** [comment]
The two artifacts are available now https://repo1.maven.org/maven2/com/google/cloud/tools/appengine-maven-plugin/2.5.1/
https://repo1.maven.org/maven2/com/google/cloud/tools/appengine-plugins-core/0.10.1/

**Pull request merged**
